### PR TITLE
always have an empty node descendant in link

### LINKED ISSUE #213: Copy&Paste HTML with empty links will crash
https://user-images.githubusercontent.com/323385/146371344-49e73f06-fbe3-4db3-a944-f35598c1a3c8.mp4

Copy the following text to slate block or SlateJSON field:

> <p>This indicator comprises historical and projected emissions estimates from the agriculture sector (CRF category 3), as well as historical emissions estimates from energy consumption in agriculture, forestry and fishing, expressed in million tonnes of carbon dioxide equivalents (MtCO<sub>2</sub>e). Historical emissions are presented at subcategory level with some aggregation (see Methodology <a href="/ims/greenhouse-gas-emissions-from-agriculture#_msocom_1"></a>for details), whereas emissions projected with existing measures and with additional measures are presented at aggregate level for the agriculture sector (CRF sector 3 only; excludes energy consumption).</p>

### PR DESCRIPTION
**Pull request by nileshgulia1**
fixes #213

### CODE REVIEW

**Review by tiberiuichim — COMMENTED** [review]
I think correct would be `editor.isInline(node) || Text.isText(node)`

**Comment by tiberiuichim** [comment]
@nileshgulia1 we need to have a clear idea on what we want with this. If I understand correctly, we want to fix nodes at a particular location, but I think that that match() does do recursion, so it may match things we don't want, as they're already inside the main block node.

**Comment by nileshgulia1** [comment]
I think here when child is empty calling createDefaultBlock should do the tick. https://github.com/eea/volto-slate/blob/fix-empty-anchor/src/utils/blocks.js#L111

**Review by tiberiuichim — COMMENTED** [review]
Please take into consideration the progressive enhancement design of the volto-slate editor. `normalizeExternalData` is supposed to be a feature of the basic editor, it shouldn't hardcode behavior from the volto text block.

The idea is this: we have the most basic level of behavior: a full text, multi-paragraph editor. Then the text "volto block", the equivalent of the draftjs Volto text block, adds a particular behavior: only one paragraph per the whole editor. But the basic capabilities should be supported by the SlateEditor component. It shouldn't decide on its own that only text belongs to it. These should be decided at the level of the Text block extensions.

This level of normalization should just make sure that the editor children are in the hierarchy: blockNodes -> inlineElements|blockNodes -> textNodes. Read on this at https://docs.slatejs.org/concepts/02-nodes#blocks-vs.-inlines

**Comment by nileshgulia1** [comment]
@tiberiuichim I'm able to fix the issue in #213 , but now I got this error RichText text widget
```
Error: Cannot resolve a DOM point from Slate point: {"path":[0,0,0],"offset":2}
    at Object.toDOMPoint (index.es.js:2171)
    at Object.toDOMRange (index.es.js:2191)
    at index.es.js:1055
    at commitHookEffectListMount (react-dom.development.js:19731)
    at commitLifeCycles (react-dom.development.js:19787)
    at commitLayoutEffects (react-dom.development.js:22803)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at commitRootImpl (react-dom.development.js:22541)
    at unstable_runWithPriority (scheduler.development.js:653)
    ```

**Comment by nileshgulia1** [comment]
Needs a new release with https://github.com/plone/volto/pull/2945

**Comment by nileshgulia1** [comment]
@tiberiuichim  This is ready!

**Review by tiberiuichim — APPROVED** [review]

**Comment by avoinea** [comment]
@nileshgulia1 we have a conflict here!

File: src/editor/plugins/Link/deserialize.js [hunk 1]
```diff
@@ -22,10 +23,15 @@ const hasValidTarget = (aEl) => {
 export const linkDeserializer = (editor, el) => {
   let parent = el;
 
-  const children = Array.from(parent.childNodes)
+  let children = Array.from(parent.childNodes)
     .map((el) => deserialize(editor, el))
     .flat();
 
+  if (isEmpty(children)) {
```
Comment (silviubogan) [inline src/editor/plugins/Link/deserialize.js:30]: I would have put this logic inside an if at the beginning of deserializeChildren because it is general behaviour (am I wrong?):

https://github.com/eea/volto-slate/blob/a4646aca793051fb14dfa1da9ba420f810747496/src/editor/deserialize.js#L90-L93
